services:
  newrelicapp:
    image: newrelicapp
    build:
      context: .
      dockerfile: NewRelicApp/Dockerfile
    environment:
      - NEW_RELIC_LICENSE_KEY=eu01xxebb2c8071cf7fa7956cffda82eFFFFNRAL
      - NEW_RELIC_APP_NAME=chuj
      - CORECLR_ENABLE_PROFILING=1
      - CORECLR_PROFILER={36032161-FFC0-4B61-B559-F6C5D41BAE5A}
      - CORECLR_NEWRELIC_HOME=/usr/local/newrelic-dotnet-agent
      - CORECLR_PROFILER_PATH=/usr/local/newrelic-dotnet-agent/libNewRelicProfiler.so
  newrelicwebapp:
    image: newrelicwebapp
    ports:
      - 8080:8080
    build:
      context: .
      dockerfile: NewRelicWebApp/Dockerfile
    environment:
      - NEW_RELIC_LICENSE_KEY=eu01xx9b78feea9becc08b021c18cd88FFFFNRAL
      - NEW_RELIC_APP_NAME=grpc-service-2
      - NEW_RELIC_ATTRIBUTES_ENABLED=true
      - NEW_RELIC_ATTRIBUTES_EXCLUDE=hostname
      - NEW_RELIC_ALLOW_ALL_HEADERS=true
      - NEW_RELIC_LOG=MyApp.log
      - CORECLR_ENABLE_PROFILING=1
      - CORECLR_PROFILER={36032161-FFC0-4B61-B559-F6C5D41BAE5A}
      - CORECLR_NEWRELIC_HOME=/usr/local/newrelic-dotnet-agent
      - CORECLR_PROFILER_PATH=/usr/local/newrelic-dotnet-agent/libNewRelicProfiler.so
      - ASPNETCORE_URLS=http://+:8080
      - ASPNETCORE_Kestrel__Endpoints__Http__Protocols=Http2
      - ASPNETCORE_Kestrel__Endpoints__Http__Url=http://*:8080
    networks:
      - grpc-network

  newrelicwebappclient:
    image: newrelicwebappclient
    ports:
      - 8081:8080
    build:
      context: .
      dockerfile: NewRelicWebAppClient/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - NEW_RELIC_LICENSE_KEY=eu01xx9b78feea9becc08b021c18cd88FFFFNRAL
      - NEW_RELIC_APP_NAME=grpc-client
      - CORECLR_ENABLE_PROFILING=1
      - CORECLR_PROFILER={36032161-FFC0-4B61-B559-F6C5D41BAE5A}
      - CORECLR_NEWRELIC_HOME=/usr/local/newrelic-dotnet-agent
      - CORECLR_PROFILER_PATH=/usr/local/newrelic-dotnet-agent/libNewRelicProfiler.so
      - ASPNETCORE_URLS=http://+:8080
      - ASPNETCORE_Kestrel__Endpoints__Http__Protocols=Http1
      - ASPNETCORE_Kestrel__Endpoints__Http__Url=http://*:8080
    networks:
      - grpc-network

networks:
  grpc-network:
    driver: bridge